### ISSUE TITLE
Get tiger192,3 hash

### ISSUE THREAD

**Issue by EddieOne** [Sembiance/mhash#12]
Hello, I'm trying to get the same hash using mhash and php with tiger192. I tried to do 3 rounds using mhash but the results are different. Is there an easy way to do this?

**Comment by dr-dimitru** [comment]
Hi @Sembiance , 
 - What the difference between `tiger192 `, `tiger192,3` and `tiger192,4` ? 
 - Same for `haval`: `haval192 `, `haval192,3` and `haval192,4`
I'm moving one project from php to js, so on php we've used `tiger192,3` and `tiger192,4` only.

**Comment by Sembiance** [comment]
@dr-dimitru I do not know exactly what the difference is. This node module just wraps the 'mhash' library. That library I did not create and I don't know what all the different hash algorithms are, I just expose them for ease of use in JS.

**Comment by dr-dimitru** [comment]
@Sembiance Maybe you can give a little explanation on this code?:
```js
var hash = require("../../index.js").hash;

var before = hash("tiger192", "abc");
var after = "";
for(var i=0;i<3;i++)
{
    for(var z=7;z>=0;z--)
    {
        after += before.substr((i*16)+(z*2), 2);
    }
}
console.log(after);
```

**Comment by Sembiance** [comment]
@dr-dimitru I whipped that up over a year ago and I'm afraid I only learned enough to be able to solve the specific problem at the time and I no longer remember how the tiger192 function really works.

I do remember that searching Google provided all the info I needed.

**Comment by dr-dimitru** [comment]
@Sembiance thank you
