### ISSUE TITLE
Support for Node.js v0.11

### ISSUE THREAD

**Issue by mcandre** [Sembiance/mhash#15]
mhash works great in Node.js v0.10, but when I upgrade to Node.js v0.11.0, mhash can no longer compile.

**Comment by Sembiance** [comment]
Ok, converted to using nan which works just fine under 0.10.x and 0.12.0 I didn't check 0.11.x but nan says it supports it so it should work fine

**Comment by marlonmantilla** [comment]
Hi @Sembiance currently having issues with [mhash with node 0.12.0](https://github.com/Sembiance/mhash/issues/16)

**Comment by mcandre** [comment]
Er, compilation against Node.js v0.12 is still broken. That commit is not sufficient to fully make the C wrapper congruent with the Node.js v0.12 engine C API.
