### ISSUE TITLE
Build fails with iojs 3.1.0 but works fine for node v0.12.7

### ISSUE THREAD

**Issue by tuananh** [Sembiance/mhash#17]
Also fails on iojs 3.2.0

I'm getting a bunch of.

~~~
error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
~~~

**Comment by Sembiance** [comment]
I have updated the 'nan' dependency to the 2.x version which is supposed to be compatible with iojs.

Could you try it again and let me know if it's fixed?

**Comment by tuananh** [comment]
@Sembiance it works now. Thanks for the fix.
