### ISSUE TITLE
node-gyp fails in El Capitan

### ISSUE THREAD

**Issue by mcandre** [Sembiance/mhash#18]
When I try to npm install mhash (any version between 2.0.0 and 2.1.3), I get a node-gyp build failure.

Could we please fix these for Mac OS X users?

Could we rewrite mhash in pure Node.js, so that we don't depend on a rather flaky build system?

**Comment by Sembiance** [comment]
I didn't write mhash, I just encapsulate it for use in nodejs. It's an open source library that's been around a long while. So I myself don't plan on re-writing mhash in pure JavaScript, though that would be nice and is somewhat tempting as it would fill a role.

As for the build error, I'll have to boot up my mac when I get the chance and take a look at what may be wrong.

**Comment by lsmoura** [comment]
This is fixed for me in https://github.com/Sembiance/mhash/pull/19. Committing the pull request, should resolve @mcandre's issue

**Comment by Sembiance** [comment]
Fixed by #19
